# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d56ccab0f3483baabea8e7bbaafcbb62c4056b06724f32367bdc04cc55f455f53f21a91d97601dd8336c15668900a1d0a712cd0a7ca61942825496e42b1d7e5

test:
  secret_key_base: 138172ecb91d3d050bbb72cc9e7f6320f07ce128cd35b08cc42d8addabf453e3d6b5d3604827b060edaeb5863a786a8f4ddf09cd3d01ef324c18479422dd30b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
